<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DenevaManagerTR.Worker</AssemblyName>
    <LangVersion>latest</LangVersion>
    <DefineConstants Condition="'$(EXCLUDE_ARTIFACT_LOGGING)' == 'true'">$(DefineConstants);EXCLUDE_ARTIFACT_LOGGING</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Artifact.Transit.Logging" Version="1.*" Condition="'$(EXCLUDE_ARTIFACT_LOGGING)' != 'true'" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DenevaManagerTR.Application\DenevaManagerTR.Application.csproj" />
    <ProjectReference Include="..\DenevaManagerTR.Core\DenevaManagerTR.Core.csproj" />
    <ProjectReference Include="..\DenevaManagerTR.Infrastructure\DenevaManagerTR.Infrastructure.csproj" />
  </ItemGroup>
</Project>